---
title: "About this site"
description: |
  This is primarily a blog for expressing my random thoughts, opinions, and the odd tutorial about R
  or pharmacometrics, but also serves as the de facto homepage for my company, Numetric GmbH, which is a member of Occams.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## A bit about me 

I'm from Cape Town, one of the world's sunnier places, and I have a PhD in pharmacology (my thesis was on the population pharmacokinetics of rifampicin, isoniazid, and pyrazinamide, key drugs in the treatment of tuberculosis) from the [University of Cape Town](https://www.uct.ac.za) - I also collected a BSc in microbiology and biochemistry, and an MSc in the pharmacoeconomics of malaria while I was there (as you do). 

Since then, I've moved around a bit. I joined [Uppsala University](https://www.uu.se) as a postdoctoral researcher in 2004, where I had the good fortune to work in the storied Department of Pharmaceutical Biosciences, one of the world's foremost centers of pharmacometrics, and then to Switzerland in 2006, to join [Novartis](https://www.novartis.com). 

In 2010, I joined Exprimo, a pharmacometrics consulting company of some renown. Sadly, it was acquired by a multinational logistics company soon after, which ran it into the ground. Everyone left, and today, it no longer exists. On the bright side, this catastrophe gave some colleagues and I the push we needed to set up shop for ourselves, and in 2015, we formed [Occams](https://www.occams.com). My family and I moved to Germany in 2019, where we remain today.

I'm a pharmacometrics consultant in my day job. I build pharmacokinetic (PK), pharmacodynamic (PD) and PK-PD models for drugs, based on clinical trial data; these models can be used to explain and predict changes in drug concentration over time, given a specific dose, and how those concentrations relate to the drug's effects (both positive and negative). I've worked on drugs in infectious diseases, oncology, diabetes, and respiratory disease, amongst others - you can find a more detailed record of what I've been up to [here](https://scholar.google.com/citations?user=p8gEvroAAAAJ&hl=en).

I try to keep active in the greater pharmacometrics community. I was elected to the Board of Directors of the [International Society of Pharmacometrics (ISoP)](https://www.go-isop.org) in 2016, and served as its President in 2019. My term ended at the end of 2021, and I'm pretty proud of what my ISoP colleagues and I managed to achieve while there. I'm currently part of the logistics team at [PAGE](https://www.page-meeting.org), sit on its Student Sponsorship committee, and have been on its Scientific Organizing Committee since 2013. I was the Novartis representative on the [DDMoRe](https://www.ddmore.foundation/) project, served briefly as its Scientific Director, and co-led the team that developed the [Thoughtflow](https://www.ddmore.foundation/thoughtflow/) concept. The success of DDMoRe is up for debate, but I'm firmly of the opinion that did some useful things (if only more people agreed).

As well as being a full-time pharmacometrics consultant in my day job, I dabble occasionally in tool development and I'm a big fan of reproducibility in research. [Census](https://github.com/kestrel99/Census) was my attempt at a run management tool for NONMEM, but it has fallen into disuse over the past few years (moral of the story - if you want to build a community around an open source tool, don't develop it in Object Pascal). I helped port [xpose4](https://uupharmacometrics.github.io/xpose4/reference/xpose4-package.html) from S-PLUS to R while at Uppsala, I maintain the [pmxTools](https://github.com/kestrel99/pmxTools) package for R, and I'm on the [nlmixr](https://github.com/nlmixr2/nlmixr2) development team (everyone should use nlmixr, it's great).

I'm on [GitHub](https://github.com/kestrel99). On social media, I can be found on [Twitter](https://www.twitter.com/justinwilkins) and [LinkedIn](https://www.linkedin.com/in/justinjwilkins/) (where I mostly just lurk). 

This blog occasionally pops up at [RWeekly.org](https://rweekly.org).
